### ISSUE TITLE
Queation about config file

### ISSUE THREAD

**Issue by mxjmtxrm** [mit-han-lab/lmquant#2]
Hi, thanks for the great work.
If there is a tutorial about how to create a custom config file, like [awq.yaml](https://github.com/mit-han-lab/lmquant/blob/main/projects/llm/configs/awq.yaml). I am wondering what is the meaning of each parameter, like s/n/z int.

**Comment by mxjmtxrm** [comment]
Here is another question about smooth code.
Why do these operations on y_range？ especially `view` and `expand`. https://github.com/mit-han-lab/lmquant/blob/c5c10897da4957cba47dd798080f5b2e1321f474/lmquant/quant/calib/calibrator/smooth.py#L289-L292

**Comment by synxlin** [comment]
Hi @mxjmtxrm, thanks for your interest in our QServe and LMQuant! About the configuration file, I am working on a detailed documentation introducing all parameters. 

As for your question about qdtype, 
- ``sint8`` indicates symmetric signed INT8, quantization range is from [-127, 127]
- ``zint8`` indicates asymmetric signed INT8 (i.e. with zero point), quantization range is from [-128, 127] with signed INT8 zero point
- ``uint8`` indicates unsigned INT8, quantization range is from [0, 255]
- ``nint8`` indicates asymmetric unsigned INT8 (i.e., with zero point), quantization range is from [0, 255] with unsigned INT8 zero point. ``zint8`` and ``nint8`` is mathematically the same (with an offset of 128). 
- you can see more details [here](https://github.com/mit-han-lab/lmquant/blob/main/lmquant/quant/data/dtype.py#L407).
- All configuration has its own Config class. Currently, you can refer to the docstrings of these config class (e.g., [WeightQuantizerConfig](https://github.com/mit-han-lab/lmquant/blob/main/lmquant/quant/quantizer/config/tensor.py#L117)).

As for your question on SmoothAttention,
- RoPE (Rotary Position Embedding) in ``transformers`` is implemented in a manner that channel *i* and channel *i+D/2* are paired (see [here](https://github.com/huggingface/transformers/blob/main/src/transformers/models/llama/modeling_llama.py#L153)). 
- In order to make SmoothAttention scale factor commutative with RoPE, we have to make sure ``scale[i]==scale[i+D/2]``. 
- SmoothAttention ``scale`` is determined by the *per-channel* activation range. In the code, ``y_range`` is a tensor with shape ``(C,)`` and can be viewed as ``(num_heads, 2, head_size / 2)`` since ``C = num_heads * head_size``.
- To make ``scale[i]==scale[i+D/2]``, we perform reduction on the ``dim=1`` on the Line 291. After reduction, ``y_range`` is in the shape of ``(num_heads, 1, head_size/2)``. By expanding to the shape ``(num_heads, 2, head_size/2)``, we let ``y_range[i]==y_range[i+D/2]``, which will lead to ``scale[i] == scale[i+D/2]``.

**Comment by mxjmtxrm** [comment]
I got it. Thanks.

**Comment by brisker** [comment]
@synxlin 

It seems that the config yaml isn't actually used by the run file [here](https://github.com/mit-han-lab/lmquant/blob/main/lmquant/llm/run.py)。


I  simply use the [yaml file here](https://github.com/mit-han-lab/lmquant/blob/main/projects/llm/configs/smoothquant/static.yaml) and just modify enabled_smooth from true to false, and when I debug the code, the flag enabled_smooth seems to be still true.
 Is there any minor bugs?

**Comment by synxlin** [comment]
Hi, @brisker. How did you set `enabled_smooth` to `false`? To disable smooth, you can set `enable_smooth` (not `enabled_smooth`) to `false` in the yaml file.

**Comment by brisker** [comment]
@synxlin 
Hi, `enable_smooth `set and problem solved.
Besides, after I run the w8a8-per-tensor static kv quantization for llama2-13b using [this line code](https://github.com/mit-han-lab/lmquant/blob/main/projects/llm/scripts/smoothquant.sh#L5), I got a folder containing model.pt and scale.pt. But the weird thing is that I can not find any quantization parameters corresponding to kv8 static per-tensor quantization, so after I convert this folder using [this code](https://github.com/mit-han-lab/qserve/blob/main/scripts/ckpt_converter/checkpoint_converter.py), and run the generated files by this, I am not even sure, whether it's w8a8-with-per-static-kv8-quantization or w8a8-with-dynamic-per-token-kv8-quantization. It seems that kv8 quantization parameters has not been used by QServe.

**Comment by synxlin** [comment]
Hi, @brisker. You are right about this since I did not save the per-tensor scale factor of KV cache in the `scale.pt`. We are still working on cleaning our code for all cases (W8A8KV8-static, etc.)

**Comment by brisker** [comment]
@synxlin 
So QServe can not support static kv quantization right now, right?

**Comment by ys-2020** [comment]
Hi @brisker , thank you for your interests in QoQ and QServe. Yes. In QServe, we mainly support dynamic quantization in the current version, and the scaling factors/zeros for kv quantization are also stored in the kv page. We found that dynamic quantization for kv cache achieves better accuracy-efficiency trade-offs.

**Comment by brisker** [comment]
@synxlin 
Thanks for your prompt reply. 

Besides, when I was reading the codes of QServe, I found that you put the rotary_pos_emb and attention in [one cuda function](https://github.com/mit-han-lab/qserve/blob/main/qserve/modeling/models/llama_w8a8_unpad.py#L183), and even the first token generation and other following token generation do not share the same cuda function, which uses [this](https://github.com/mit-han-lab/qserve/blob/main/qserve/modeling/models/llama_w8a8_unpad.py#L183) and [this](https://github.com/mit-han-lab/qserve/blob/main/qserve/modeling/models/llama_w8a8_unpad.py#L247) respectively.

So my question is:
1. why do you couples rotary_pos_emb with attention? It seems that if qserve needs to support more models, and if more kinds of rotary_pos_emb happens, **this coupling  can make the codes not flexible.**  In VLLM [here](https://github.com/vllm-project/vllm/blob/main/vllm/model_executor/models/llama.py#L162) and [here](https://github.com/vllm-project/vllm/blob/main/vllm/model_executor/models/llama.py#L163), these two are seperated.

2. what is the difference between the two functions mentioned above.(first token and non-first-token generation cuda function)

**Comment by brisker** [comment]
@synxlin 

**w4a8kv4-gs128**  means
per-channel-static-w4
per-token-dynamic-a8
per-head-dynamic-kv4,     right?

In your latest version of paper,  **is there any minor slip of pen in the following part ?**
![image](https://github.com/mit-han-lab/lmquant/assets/13804492/dd70ed1a-8f07-411b-b188-6d6c531e38c6)

**Comment by synxlin** [comment]
@brisker Thank you for helping us find this typo. We will fix it in the next version of our paper.

**Comment by brisker** [comment]
@synxlin 
In your paper, you mentioned dynamic per_head kv_cache quantization with scales and zero_points.
Given a kv_cache value with shape` [batchsize, attention_head_nums, token_num, hidden_dim/attention_head_nums]`, is your quantization scales and zero_points in shape:
`[batchsize, attention_head_num,token_num] `???

( I run your kv4 quanti codes on wikitext test on llama, the float kv_cache data is in shape `[2048,4096],` and the scales are in shape  `[2048,1,32,1]` )

**Comment by synxlin** [comment]
@brisker, for your questions:
1. You are right about KV cache quantization. Every `hidden_dim/attention_head_nums` elements share the same quantization scale and zero point. 
2. The zero-shot accuracy in Table.3 is of Llama-2 (You can see from the top-left cell in the table).
3. Yes, the KV cache quantization is simple RTN quantization after SmoothAttention.
4. We currently use `lm_eval` to evaluate zero-shot accuracy; you check code [here](https://github.com/mit-han-lab/lmquant/blob/main/lmquant/llm/eval.py#L98C41-L98C56). You can refer to `lm_eval` documentation to see how to parse the local dataset to the `simple_evaluate()`.

**Comment by brisker** [comment]
Thanks for your prompt reply!

I notice that the w4a8 model files size is half of that of w8a8, and w8a8 is half that of fp16, but the **file dtype is still int8 in w4a8kv4** models, and the element num is half of w8a8 and fp16. So you just store N/2 int8 numbers to represent N int4 numbers( original tensor numbers are N), right?  How did you do this? Where is the corresponding code?
@synxlin
